### ISSUE TITLE
WebLogic 12.2.x support

### ISSUE THREAD

**Issue by EricPMulligan** [arquillian/arquillian-container-wls#32]
Will there be support for WebLogic 12.2.1.2.0 in the near future?

**Comment by bartoszmajsak** [comment]
Hi @EricPMulligan, thanks for bringing up this question. I assume `12.1.2` version of our adapters are not working for you? We don't have anyone in the team specifically working on this module, but if you would be up for contribution I can help you to work on this feature. Would this be an option?

**Comment by EricPMulligan** [comment]
I haven't completed my testing to see if the 12.1.2 version of the adapter works, I was only curious. I may be interested in contributing. Let me do further testing and I'll get back to you on this.

**Comment by bartoszmajsak** [comment]
Awesome! I'm around if you need anything. Thanks for spending time on this.

**Comment by bidzhao** [comment]
When will this be fixed?
